### ISSUE TITLE
the mut.py in the python3 build is broken

### ISSUE THREAD

**Issue by rlgomes** [mutpy/mutpy#13]
https://pypi.python.org/packages/1f/2e/bb5128877b8c05e243445e83c0848563b3c47ee431cfaf1a6e819104fab7/MutPy-0.5.0-py3-none-any.whl#md5=b5dc2f24666519a4ebde9b1e8ae1b202

open that up and see whats in the mut.py file as it looks like so:

```python
#!/Users/konradhalas/dev/virtualenvs/mutpy/bin/python

import sys
from mutpy import commandline

if __name__ == '__main__':
    commandline.main(sys.argv)
```

which is obviously referencing your local virtualenv.

**Comment by konradhalas** [comment]
Thank you @rlgomes for reporting this! This is my fault. Should be fixed now (v0.5.1).

**Comment by rlgomes** [comment]
@konradhalas  AWESOME and thanks!

**Comment by m3r3lin** [comment]
i have this issue , what am i doing?

**Comment by rlgomes** [comment]
@m3r3lin are you running the older 0.5.0 version ? just upgrade to the 0.5.1 and it should work:

```
> pip install mutpy
...

> cat `which mut.py`
#!/Users/rlgomes/workspace/python3/mutpy-test/env/bin/python3

import sys
from mutpy import commandline

if __name__ == '__main__':
    commandline.main(sys.argv)
```

**Comment by m3r3lin** [comment]
i use last version mutpy
Successfully installed Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.13 mutpy-0.5.1

when  use this command:
mut.py --target calculator --unit-test test_calculator -m
get this error:

whaTraceback (most recent call last):
  File "D:\python project\lasttest\venv\Scripts\mut.py", line 4, in <module>
    from mutpy import commandline
ImportError: No module named mutpyt

**Comment by m3r3lin** [comment]
@rlgomes please answer me
my time is limited

**Comment by reenakesari** [comment]
How to solve this problem?

#!c:\users\reena\pycharmprojects\calc\venv\scripts\python.exe

import sys
from mutpy import commandline

if __name__ == '__main__':
    commandline.main(sys.argv)

**Comment by jairajrouth** [comment]
Hi @reenakesari ,
did you solve your problem ? I am new in running mutation testing. I ran mut.py --target (..........) and nothing happens just a file name "mut.py" opens up with the same code what's mentioned in your comment. Any fix ??

**Comment by GustavoCampoz** [comment]
I run "mut.py --target ... --unit-test test_... -m" and open a cmd and close it right away showing no results
