### ISSUE TITLE
Error when use --report-html

### ISSUE THREAD

**Issue by dunossauro** [mutpy/mutpy#25]
Hello everybody.

I'm trying use HTML report using the flag `--report-html` and receive a template not found. I find the [template](https://github.com/mutpy/mutpy/blob/master/mutpy/templates/detail.html) on master branch and a found the instruction:

```Python
templates_path = os.path.join(os.path.dirname(__file__), 'templates')
```

I'm use the version:

```sh
$ mut.py --version
mut.py 0.5.1
```

```Python
  File "/.../.local/share/virtualenvs/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: detail.html
```
------------------------------------------------------------

After that a try clone the repository and paste the templates path in my venv and works good.

After that a check the [setup file](https://github.com/mutpy/mutpy/blob/master/setup.py#L27) and maybe can include the sub-path using package_data parameter in setup.py to copy templates path.

Thanks a lot for library and sorry for my english.

:heart:

**Comment by konradhalas** [comment]
@dunossauro thank you for your report! I will check it, I thought it should works after I added templates to `MANIFEST.in` file.

@phihos could you also reproduce this issue?

**Comment by phihos** [comment]
Yes I can reproduce it. @dunossauro Thanks for reporting. I will get to the bottom of this.

**Comment by jbean96** [comment]
Sorry to re-open this. But I just did a `pip install mutpy` and it doesn't come with the templates folder. Perhaps the package didn't get updated on PyPI since this fix?

By the way the version that was installed was 0.5.1 and my environment has Python 3.6.8

**Comment by phihos** [comment]
Can you try it with the new v0.6.0?
