### ISSUE TITLE
Command Does not work when test file is in tests folder

### ISSUE THREAD

**Issue by ashfaq92** [mutpy/mutpy#45]
`$ mut.py --target calculator --unit-test test_calculator -m`
this command only works when `test_calculator` is on root. But it is a common practice to place test files in separate 'tests' package/folder. This command does not work for that. I have also tried:
`$ mut.py --target calculator --unit-test tests/test_calculator -m`
But that also does not work as well.

**Comment by phihos** [comment]
Have you tried ```mut.py --target calculator --unit-test tests.test_calculator -m```?

**Comment by ashfaq92** [comment]
yes it worked! Thank you reply. Sorry for dumb question. This was a question rather than an issue.
