### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by divya31** [mutpy/mutpy#51]
Hi, 

The issue I am currently facing is that when Mutpy is used with -m option (or --show-mutants) 
it runs into a "RecursionError: maximum recursion depth exceeded" error and it end abruptly without giving a mutation score after this. 

However, if I run Mutpy without the -m options, it works perfectly fine by giving the mutation scores, numbers of generated and killed mutants etc even when the number of mutants generated is considerable large( > 100) .

I need the -m option as I would like to know which lines of the source code is mutated using whcih mutation operator.
(python virtual environment created using python3
mutpy version : mut.py 0.6.0 
python version : Python 3.6.8
ubuntu version: 18.04.03 LTS)

beginning screen of recursion error
![image](https://user-images.githubusercontent.com/5357083/67625616-a0bf5580-f840-11e9-9ff3-1a3ed953d8d3.png)

end screen of the recursion error
![image](https://user-images.githubusercontent.com/5357083/67625630-cc424000-f840-11e9-9a42-817e8a52b8c0.png)

Can anyone please let me know if I am making a mistake (I am new to python and mutation) or if the tool does not support -m option when the number of mutants generated are considerable large (around > 50 )

**Comment by divya31** [comment]
> Hi,
> 
> The issue I am currently facing is that when Mutpy is used with -m option (or --show-mutants)
> it runs into a "RecursionError: maximum recursion depth exceeded" error and it end abruptly without giving a mutation score after this.
> 
> However, if I run Mutpy without the -m options, it works perfectly fine by giving the mutation scores, numbers of generated and killed mutants etc even when the number of mutants generated is considerable large( > 100) .
> 
> I need the -m option as I would like to know which lines of the source code is mutated using whcih mutation operator.
> (python virtual environment created using python3
> mutpy version : mut.py 0.6.0
> python version : Python 3.6.8
> ubuntu version: 18.04.03 LTS)
> 
> beginning screen of recursion error
> ![image](https://user-images.githubusercontent.com/5357083/67625616-a0bf5580-f840-11e9-9ff3-1a3ed953d8d3.png)
> 
> end screen of the recursion error
> ![image](https://user-images.githubusercontent.com/5357083/67625630-cc424000-f840-11e9-9a42-817e8a52b8c0.png)
> 
> Can anyone please let me know if I am making a mistake (I am new to python and mutation) or if the tool does not support -m option when the number of mutants generated are considerable large (around > 50 )

**Comment by phihos** [comment]
Hi, sorry for the long delay. I am currently very busy.
Can you try again with the branch "bugfix/fix-numpy-import-issue"?
```bash
git clone https://github.com/mutpy/mutpy.git
cd mutpy
git checkout bugfix/fix-numpy-import-issue
cd ..
git clone git@github.com:pydicom/pydicom.git
cd pydicom
virtualenv venv
source venv/bin/activate
pip install numpy  # maybe not necessary
pip install ../mutpy
mut.py --target pydicom --unit-test pydicom.tests -m --runner pytest
```
The tests are still running, but it seems to work.

**Comment by phihos** [comment]
Ok the root cause seems to be astmonkey making subtle chnages to the ast when generating the source code from ast.
I worked around that by making a deepcopy of the ast and only giving the copy to astmonkey. Could you verify that it works by running the tests with the lastest "bugfix/fix-numpy-import-issue" branch?

**Comment by divya31** [comment]
Hi Phihos,

I use the project from pydicom project from https://github.com/pydicom/pydicom.git.
I get a "SyntaxError: from __future__ imports must occur at the beginning of the file" in the "bugfix/fix-numpy-import-issue" branch
![image](https://user-images.githubusercontent.com/5357083/69008777-9fb8aa00-094e-11ea-8b69-4fe8801fd72f.png)

**Comment by phihos** [comment]
Great! The future import bug is already documented here: https://github.com/mutpy/mutpy/issues/24. Sadly this is not trivial to fix. I will attempt to solve this issue when I have more time on my hands.
I will now merge these changes and release a new Mutpy version.

**Comment by phihos** [comment]
MutPy v0.6.1 is out.
